### PR TITLE
使用llvmctor来实现stackmap初始化

### LINKED ISSUE #304: 使用llvmctor来实现stackmap初始化

### PR DESCRIPTION
**Pull request by Chronostasys**
Fixes #304

### CODE REVIEW

**Comment by Chronostasys** [comment]
Fuck lld!

**Comment by Chronostasys** [comment]
this pr also remove lld completly, as it doesn't seems to work with `llvm.global_ctors`

**Review by RINNE-TAN — APPROVED** [review]
LGTM

**Comment by Chronostasys** [comment]
Have to replace lld with ld on linux. As llv, `ctors` doesn't seem to work on  executable linked by lld. Maybe some special linker flag would help, but I'm not familiar with it.

Anyway, `ctors` works just fine with ld on linux.

**Review by RINNE-TAN — APPROVED** [review]
LGTM

**Pull request merged**
