### PR TITLE
fix: where and pub fmt

### PR DESCRIPTION
**Pull request by RINNE-TAN**
fix: where and pub fmt

### CODE REVIEW

**Review by Chronostasys — DISMISSED** [review]
LGTM!

**Review by MoonOld — APPROVED** [review]
LGTM!

**Review by Chronostasys — DISMISSED** [review]
LGTM!

**Review by Chronostasys — APPROVED** [review]
LGTM!

**Review by MoonOld — APPROVED** [review]
balabala

**Pull request merged**
